FROM php:8.2.9-bullseye

## Diretório da aplicação
ARG APP_DIR=/var/www/app

## Versão da Lib do Redis para PHP
ARG REDIS_LIB_VERSION=5.3.7

### apt-utils é um extensão de recursos do gerenciador de pacotes APT
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    apt-utils \
    supervisor

# dependências recomendadas de desenvolvido para ambiente linux
RUN apt-get update && apt-get install -y \
    zlib1g-dev \
    libzip-dev \
    zip \
    unzip \
    libpng-dev \
    libonig-dev \
    libpq-dev \
    libxml2-dev \
    nano \
    cron \
    gnupg2 \
    wget \
    libpq-dev \
    lsb-release

RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'  && \
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg

RUN apt-get update && apt-get install -y postgresql-client-16

RUN docker-php-ext-install mysqli pdo pdo_mysql pdo_pgsql pgsql session xml mbstring exif pcntl bcmath gd zip

# habilita instalação do Redis
RUN pecl install redis-${REDIS_LIB_VERSION} \
    && docker-php-ext-enable redis

RUN docker-php-ext-install zip iconv simplexml pcntl gd fileinfo

### Instalar e Habilitar o Swoole
RUN pecl install swoole
RUN docker-php-ext-enable swoole

# Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY ./docker/supervisord/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY ./docker/php/extra-php.ini "$PHP_INI_DIR/99_extra.ini"

WORKDIR $APP_DIR
RUN cd $APP_DIR

RUN chown -R www-data:www-data $APP_DIR

COPY --chown=www-data:www-data ./ .

RUN composer install --no-interaction --no-dev --optimize-autoloader

### OCTANE
RUN php artisan octane:install --server=swoole

RUN php artisan optimize

### Comandos úteis para otimização da aplicação
#RUN php artisan config:cache
#RUN php artisan route:cache
#RUN php artisan view:cache
#RUN php artisan event:cache

### NGINX
RUN apt-get install nginx -y
RUN rm -rf /etc/nginx/sites-enabled/* && rm -rf /etc/nginx/sites-available/*
COPY ./docker/nginx/sites.conf /etc/nginx/sites-enabled/default.conf
COPY ./docker/nginx/error.html /var/www/html/error.html

RUN apt-get clean && rm -rf /var/lib/apt/lists/*
# RUN apt update -y && apt install nano git -y

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
